apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  labels:
    app: spring
  namespace: draft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: zhiyong.azurecr.io/spring-petclinic-draft:latest
          ports:
            - containerPort: 8080